version: '3.7'

services:

  furnitureshop_api:
    image: furnitureshop_api
    depends_on:
      - "furniture_db"
    container_name: furnitreshop_api
    ports: 
      - "1001:80"
    build:
      context: .
      dockerfile: DockerfileApi
    networks:
      - dev

  furnitureshop_merchant_api:
    image: furnitureshop_merchant_api
    depends_on:
      - "furniture_db"
    container_name: furnitureshop_merchant_api
    ports:
      - "1009:80"
    build:
      context: .
      dockerfile: DockerfileMerchant
    networks:
      - dev

  furnitureshop_client_api:
    image: furnitureshop_client_api
    depends_on:
      - "furniture_db"
    container_name: furnitureshop_client_api
    ports: 
      - "1005:80"
    build:
       context: .
       dockerfile: DockerfileClient
    networks:
      - dev

  furnitureshop_admin_api:
    image: furnitureshop_admin_api
    depends_on:
      - "furniture_db"
    container_name: furnitureshop_admin_api
    ports:
      - "8032:80"
    build:
      context: .
      dockerfile: DockerfileAdmin
    networks:
      - dev

  furnitureshop_files_api:
    image: furnitureshop_files_api
    container_name: furnitureshop_files_api
    ports:
      - "8034:80"
    build:
      context: .
      dockerfile: DockerfileFiles
    networks: 
      - dev

  furniture_db:
    image: postgres:latest
    container_name: furniture_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - dev

networks:
  dev:
    driver: bridge 
    

volumes:
  customer_data:
  pgadmin: