version: '3.7'

services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - dev
    restart: unless-stopped

  furnitureshop_merchant_api:
    image: furnitureshop_merchant_api
    depends_on:
      - "furniture_db"
    container_name: furnitureshop_merchant_api
    ports:
      - "8031:80"
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
      # - ConnectionString=host=dockerapi_db;port=5432;database=dockerdb;username=postgres;password=postgres;
    networks:
      - dev

  furniture_db:
    image: postgres:latest
    container_name: furniture_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - dev

networks:
  dev:
    driver: bridge 
    

volumes:
  customer_data:
  pgadmin: